[package]
name = "u_are_errors"
version = "0.1.0"
edition = "2024"


[dependencies]
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"

# [profile.release]
# rustflags = ["-C", "link-args=/DEBUG:NONE"]
# debug = false
